//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patagames.Pdf.Net.Controls.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patagames.Pdf.Net.Controls.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        internal static string btnActualSizeText {
            get {
                return ResourceManager.GetString("btnActualSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level to the page&apos;s actual size.
        /// </summary>
        internal static string btnActualSizeToolTipText {
            get {
                return ResourceManager.GetString("btnActualSizeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string btnCopyText {
            get {
                return ResourceManager.GetString("btnCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the clipboard.
        /// </summary>
        internal static string btnCopyToolTipText {
            get {
                return ResourceManager.GetString("btnCopyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        internal static string btnFirstPageText {
            get {
                return ResourceManager.GetString("btnFirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the first page of the file.
        /// </summary>
        internal static string btnFirstPageToolTipText {
            get {
                return ResourceManager.GetString("btnFirstPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Height.
        /// </summary>
        internal static string btnFitHeightText {
            get {
                return ResourceManager.GetString("btnFitHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level so the page height fits the window height.
        /// </summary>
        internal static string btnFitHeightToolTipText {
            get {
                return ResourceManager.GetString("btnFitHeightToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Page.
        /// </summary>
        internal static string btnFitPageText {
            get {
                return ResourceManager.GetString("btnFitPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level so one full page fits in the window.
        /// </summary>
        internal static string btnFitPageToolTipText {
            get {
                return ResourceManager.GetString("btnFitPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        internal static string btnFitWidthText {
            get {
                return ResourceManager.GetString("btnFitWidthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level so the page width fits the window width.
        /// </summary>
        internal static string btnFitWidthToolTipText {
            get {
                return ResourceManager.GetString("btnFitWidthToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        internal static string btnLastPageText {
            get {
                return ResourceManager.GetString("btnLastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the last page of the file.
        /// </summary>
        internal static string btnLastPageToolTipText {
            get {
                return ResourceManager.GetString("btnLastPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Horizontal.
        /// </summary>
        internal static string btnModeHorizontalText {
            get {
                return ResourceManager.GetString("btnModeHorizontalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages continuously with horizontal scrolling enabled.
        /// </summary>
        internal static string btnModeHorizontalToolTipText {
            get {
                return ResourceManager.GetString("btnModeHorizontalToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page.
        /// </summary>
        internal static string btnModeSingleText {
            get {
                return ResourceManager.GetString("btnModeSingleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View one page at time.
        /// </summary>
        internal static string btnModeSingleToolTipText {
            get {
                return ResourceManager.GetString("btnModeSingleToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Facing.
        /// </summary>
        internal static string btnModeTilesText {
            get {
                return ResourceManager.GetString("btnModeTilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages side-by-side with continuous scrolling enabled.
        /// </summary>
        internal static string btnModeTilesToolTipText {
            get {
                return ResourceManager.GetString("btnModeTilesToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Vertical.
        /// </summary>
        internal static string btnModeVerticalText {
            get {
                return ResourceManager.GetString("btnModeVerticalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages continuously with vertical scrolling enabled.
        /// </summary>
        internal static string btnModeVerticalToolTipText {
            get {
                return ResourceManager.GetString("btnModeVerticalToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string btnNextPageText {
            get {
                return ResourceManager.GetString("btnNextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward one page.
        /// </summary>
        internal static string btnNextPageToolTipText {
            get {
                return ResourceManager.GetString("btnNextPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string btnOpenText {
            get {
                return ResourceManager.GetString("btnOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open a PDF file.
        /// </summary>
        internal static string btnOpenToolTipText {
            get {
                return ResourceManager.GetString("btnOpenToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string btnPreviousPageText {
            get {
                return ResourceManager.GetString("btnPreviousPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back one page.
        /// </summary>
        internal static string btnPreviousPageToolTipText {
            get {
                return ResourceManager.GetString("btnPreviousPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string btnPrintText {
            get {
                return ResourceManager.GetString("btnPrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to print the PDF file.
        /// </summary>
        internal static string btnPrintToolTipText {
            get {
                return ResourceManager.GetString("btnPrintToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Left.
        /// </summary>
        internal static string btnRotateLeftText {
            get {
                return ResourceManager.GetString("btnRotateLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the page view 90 degrees counterclockwise.
        /// </summary>
        internal static string btnRotateLeftToolTipText {
            get {
                return ResourceManager.GetString("btnRotateLeftToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Right.
        /// </summary>
        internal static string btnRotateRightText {
            get {
                return ResourceManager.GetString("btnRotateRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the page view 90 degrees clockwise.
        /// </summary>
        internal static string btnRotateRightToolTipText {
            get {
                return ResourceManager.GetString("btnRotateRightToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string btnSelectAllText {
            get {
                return ResourceManager.GetString("btnSelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the entire document.
        /// </summary>
        internal static string btnSelectAllToolTipText {
            get {
                return ResourceManager.GetString("btnSelectAllToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string btnZoomComboText {
            get {
                return ResourceManager.GetString("btnZoomComboText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level to a specific value.
        /// </summary>
        internal static string btnZoomComboToolTipText {
            get {
                return ResourceManager.GetString("btnZoomComboToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string btnZoomInText {
            get {
                return ResourceManager.GetString("btnZoomInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the zoom level.
        /// </summary>
        internal static string btnZoomInToolTipText {
            get {
                return ResourceManager.GetString("btnZoomInToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string btnZoomOutText {
            get {
                return ResourceManager.GetString("btnZoomOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the zoom level.
        /// </summary>
        internal static string btnZoomOutToolTipText {
            get {
                return ResourceManager.GetString("btnZoomOutToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set the document property instead of using LoadDocument method set the AllowSetDocument property to True. Please read the documentation before you do it..
        /// </summary>
        internal static string err0001 {
            get {
                return ResourceManager.GetString("err0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page index is out of range..
        /// </summary>
        internal static string err0002 {
            get {
                return ResourceManager.GetString("err0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InfoHeader {
            get {
                return ResourceManager.GetString("InfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        internal static string menuItemMatchCase {
            get {
                return ResourceManager.GetString("menuItemMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        internal static string menuItemMatchWholeWord {
            get {
                return ResourceManager.GetString("menuItemMatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Files (*.pdf)|*.pdf.
        /// </summary>
        internal static string OpenDialogFilter {
            get {
                return ResourceManager.GetString("OpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string searchLblnfo {
            get {
                return ResourceManager.GetString("searchLblnfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed page {0} / {1}.
        /// </summary>
        internal static string txtPrinting {
            get {
                return ResourceManager.GetString("txtPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string txtPrintingStop {
            get {
                return ResourceManager.GetString("txtPrintingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current print job?.
        /// </summary>
        internal static string txtPromptPrintAbort {
            get {
                return ResourceManager.GetString("txtPromptPrintAbort", resourceCulture);
            }
        }
    }
}
